services:
  api:
    container_name: c0mmunify_test_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=c0mmunify
      - PGHOST=db
      - PGPASSWORD=verysecurepassword
      - PGDATABASE=ourdb
      - PGPORT=5432
    depends_on:
      - db
    tty: true

  db:
    container_name: c0mmunify_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=ourdb
      - POSTGRES_PASSWORD=verysecurepassword
      - POSTGRES_USER=c0mmunify
volumes:
  test_db:
networks:
  default:
    name: c0mmunify_test_api
