services:
  api:
    container_name: c0mmunify_dev_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=nplatton
      - PGHOST=ep-divine-rain-338764.eu-central-1.aws.neon.tech
      - PGPASSWORD=oFxI9SdRg2kZ
      - PGDATABASE=neondb
      - PGPORT=5432
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    container_name: c0mmunify_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=neondb
      - POSTGRES_PASSWORD=oFxI9SdRg2kZ
volumes:
  dbdata:
networks:
  default:
    name: c0mmunify_api
