version: "3"
services:
  api:
    image: node:latest
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code

  db:
    image: postgres:latest
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
